//! Canonical JSON number formatting — an exact port of the C reference's
//! number printer (`json_number` in `core/libmusicpack/src/manifest.c`).
//!
//! Two layers:
//!
//! 1. [`format_json_number`] — the manifest writer's number format:
//!    integral values within ±9.2e18 print as plain integers (`%lld`),
//!    everything else falls through to `%.8g`.
//! 2. [`format_g`] — an exact port of C `printf("%.8g", v)`: 8 significant
//!    digits, round-half-even on the *exact* decimal expansion of the
//!    double, `%e` style when the (adjusted) exponent is < −4 or ≥ 8,
//!    trailing zeros stripped.
//!
//! Rust's default float formatting is shortest-round-trip and is **not**
//! equivalent (e.g. `0.1` → `"0.1"` in both, but `1e-5` → `"0.00001"`
//! in Rust vs `"1e-05"` in C, and 9-digit values get rounded differently).
//! Byte-identical canonical manifests therefore require this port.
//!
//! Correctness strategy: the exact decimal expansion of an IEEE-754 double
//! is computed with small arbitrary-precision arithmetic, rounded once, and
//! formatted per C `%g` rules. The behaviour is pinned by `tests/data/
//! g8_c_reference.txt`, a table of `<bits> <output>` vectors generated by
//! running the real C `snprintf` (see `tools/g8_probe.c` for regeneration).

/// Formats a number the way the canonical manifest writer does.
///
/// Port of `json_number`:
///
/// ```c
/// if (v == (double)(long long)v && v >= -9.2e18 && v <= 9.2e18)
///     snprintf(tmp, sizeof tmp, "%lld", (long long)v);
/// else
///     snprintf(tmp, sizeof tmp, "%.8g", v);
/// ```
///
/// Note that this means integral doubles inside the range always print as
/// integers — `123456789.0` prints as `"123456789"`, never as
/// `"1.2345679e+08"` — and that `-0.0` prints as `"0"`.
pub fn format_json_number(v: f64) -> String {
    // Written as explicit comparisons on purpose: this is a direct port of
    // the C condition `v == (double)(long long)v && v >= -9.2e18 &&
    // v <= 9.2e18`, and the ±9.2e18 bound is the reference's behaviour.
    #[allow(clippy::manual_range_contains)]
    if v.fract() == 0.0 && v >= -9.2e18 && v <= 9.2e18 {
        // Within ±9.2e18 the cast to i64 is exact for integral values
        // (9.2e18 < i64::MAX ≈ 9.223e18), matching the C `(long long)` cast.
        format!("{}", v as i64)
    } else {
        format_g(v)
    }
}

/// Formats `v` exactly as C `printf("%.8g", v)` does.
///
/// Non-finite inputs render like glibc: `inf`, `-inf`, `nan` (reachable
/// only through unknown-field numbers, which are not range-validated).
pub fn format_g(v: f64) -> String {
    format_g_precision(v, 8)
}

/// Formats `v` exactly as C `printf("%.{precision}g", v)` does.
///
/// Used for canonical manifest numbers (precision 8) and for the waveform
/// duration warning, whose C format string is `%g` (precision 6).
pub fn format_g_precision(v: f64, precision: usize) -> String {
    debug_assert!(precision >= 1);
    if v.is_nan() {
        return if v.is_sign_negative() {
            "-nan".to_string()
        } else {
            "nan".to_string()
        };
    }
    if v.is_infinite() {
        return if v < 0.0 {
            "-inf".to_string()
        } else {
            "inf".to_string()
        };
    }

    let sign = if v.is_sign_negative() && v != 0.0 {
        "-"
    } else {
        ""
    };

    // Decompose: |v| = m * 2^e2 with m an integer (53 bits for normals,
    // fewer for subnormals).
    let bits = v.abs().to_bits();
    let raw_exp = ((bits >> 52) & 0x7ff) as i32;
    let frac = bits & 0x000f_ffff_ffff_ffff;
    let (m, e2) = if raw_exp == 0 {
        (frac, -1074i32)
    } else {
        (frac | (1u64 << 52), raw_exp - 1075)
    };

    // Exact decimal digits of |v| and the adjusted exponent X (position of
    // the leading digit, i.e. |v| = 0.D1D2... * 10^(X+1)).
    let (digits, x) = if m == 0 {
        (vec![0u8], 0)
    } else {
        exact_digits(m, e2)
    };
    let (mut digits, x) = round_to(digits, x, precision);

    // %g strips trailing zeros from the fractional portion. In %f style,
    // zeros at or left of the decimal point (integer part) are never
    // stripped; in %e style only the leading digit is "integer".
    #[allow(clippy::manual_range_contains)]
    if x < -4 || x >= precision as i32 {
        while digits.len() > 1 && *digits.last().expect("non-empty") == 0 {
            digits.pop();
        }
    } else {
        let point = (x + 1).max(1) as usize;
        while digits.len() > point && *digits.last().expect("non-empty") == 0 {
            digits.pop();
        }
    }

    // %g switches between %e and %f style: %e when the adjusted exponent
    // is < -4 or >= the precision. (Kept as explicit comparisons to
    // mirror the C rule; clippy's range suggestion obscures the port.)
    #[allow(clippy::manual_range_contains)]
    if x < -4 || x >= precision as i32 {
        // %e style: d.ddd…e±XX (exponent at least two digits).
        let mut out = String::with_capacity(16);
        out.push_str(sign);
        out.push((b'0' + digits[0]) as char);
        if digits.len() > 1 {
            let frac: String = digits[1..].iter().map(|&d| (b'0' + d) as char).collect();
            out.push('.');
            out.push_str(&frac);
        }
        out.push('e');
        if x < 0 {
            out.push('-');
        } else {
            out.push('+');
        }
        out.push_str(&format!("{:02}", x.abs()));
        out
    } else {
        // %f style.
        let mut out = String::with_capacity(16);
        out.push_str(sign);
        if x >= 0 {
            let int_digits = ((x + 1) as usize).min(digits.len());
            for &d in &digits[..int_digits] {
                out.push((b'0' + d) as char);
            }
            if int_digits < digits.len() {
                out.push('.');
                for &d in &digits[int_digits..] {
                    out.push((b'0' + d) as char);
                }
            }
        } else {
            out.push_str("0.");
            for _ in 0..(-x - 1) {
                out.push('0');
            }
            for &d in &digits {
                out.push((b'0' + d) as char);
            }
        }
        out
    }
}

/// Exact decimal expansion of `m * 2^e2`, returning the digit string
/// (most significant first, no trailing zeros beyond exactness) and the
/// adjusted exponent `X`.
fn exact_digits(m: u64, e2: i32) -> (Vec<u8>, i32) {
    if e2 >= 0 {
        let mut big = Big::from_u64(m);
        big.shl_bits(e2 as u32);
        let digits = big.to_decimal();
        let x = digits.len() as i32 - 1;
        (digits, x)
    } else {
        let k = (-e2) as u32;
        let mut big = Big::from_u64(m);
        big.mul_pow5(k);
        let digits = big.to_decimal();
        // value = N / 10^k where N has `digits.len()` digits.
        let x = digits.len() as i32 - 1 - k as i32;
        (digits, x)
    }
}

/// Rounds an exact digit string to `p` significant digits with
/// round-half-to-even (the rounding C's correctly-rounded `printf` uses on
/// exact decimal values). Returns the (possibly carried) digits and
/// adjusted exponent.
fn round_to(digits: Vec<u8>, x: i32, p: usize) -> (Vec<u8>, i32) {
    if digits.len() <= p {
        return (digits, x);
    }
    let kept: Vec<u8> = digits[..p].to_vec();
    let round_up = {
        let first_dropped = digits[p];
        match first_dropped.cmp(&5) {
            std::cmp::Ordering::Greater => true,
            std::cmp::Ordering::Less => false,
            std::cmp::Ordering::Equal => {
                // Exact tie only when every remaining digit is zero;
                // otherwise the tail is strictly greater than 5.
                if digits[p + 1..].iter().all(|&d| d == 0) {
                    kept[p - 1] % 2 == 1 // half-to-even
                } else {
                    true
                }
            }
        }
    };
    if !round_up {
        return (kept, x);
    }
    // Increment with carry.
    let mut kept = kept;
    let mut i = p;
    loop {
        if i == 0 {
            // 999… → 1000… with exponent bump.
            let mut carried = vec![1u8];
            carried.extend(std::iter::repeat_n(0u8, p));
            return (carried, x + 1);
        }
        i -= 1;
        if kept[i] == 9 {
            kept[i] = 0;
        } else {
            kept[i] += 1;
            break;
        }
    }
    (kept, x)
}

/// Minimal little-endian base-2³² bignum, just enough for exact decimal
/// expansion of doubles (m ≤ 2⁵³, shifts up to ~971 bits, ×5¹⁰⁷⁴).
struct Big(Vec<u32>);

impl Big {
    fn from_u64(v: u64) -> Big {
        Big(vec![v as u32, (v >> 32) as u32])
    }

    fn shl_bits(&mut self, n: u32) {
        if n >= 32 {
            let limbs = n / 32;
            let rest = n % 32;
            if limbs > 0 {
                let mut shifted = vec![0u32; limbs as usize];
                shifted.extend_from_slice(&self.0);
                self.0 = shifted;
            }
            self.shl_bits(rest);
            return;
        }
        if n == 0 {
            return;
        }
        let mut carry = 0u32;
        for limb in &mut self.0 {
            let new_carry = *limb >> (32 - n);
            *limb = (*limb << n) | carry;
            carry = new_carry;
        }
        if carry != 0 {
            self.0.push(carry);
        }
    }

    fn mul_small(&mut self, m: u32) {
        let mut carry = 0u64;
        for limb in &mut self.0 {
            let prod = *limb as u64 * m as u64 + carry;
            *limb = prod as u32;
            carry = prod >> 32;
        }
        if carry != 0 {
            self.0.push(carry as u32);
        }
    }

    fn mul_pow5(&mut self, mut k: u32) {
        // 5^13 = 1220703125 < 2^32, so 13 factors fit in one small multiply.
        while k >= 13 {
            self.mul_small(1220703125);
            k -= 13;
        }
        for _ in 0..k {
            self.mul_small(5);
        }
    }

    /// Decimal digits, most significant first.
    fn to_decimal(&self) -> Vec<u8> {
        if self.0.iter().all(|&l| l == 0) {
            return vec![0];
        }
        let mut quotient = self.0.clone();
        let mut groups: Vec<u32> = Vec::new(); // base-1e9 groups, little-endian
        while !quotient.iter().all(|&l| l == 0) {
            let (q, r) = divmod_small(&mut quotient, 1_000_000_000);
            groups.push(r);
            let _ = q;
        }
        let mut digits = Vec::with_capacity(groups.len() * 9);
        // Most significant group without zero padding.
        let top = *groups.last().expect("non-empty");
        let mut buf = [0u8; 9];
        let mut n = 0;
        let mut t = top;
        while t > 0 {
            buf[n] = (t % 10) as u8;
            t /= 10;
            n += 1;
        }
        for i in (0..n).rev() {
            digits.push(buf[i]);
        }
        // Remaining groups, zero-padded to 9.
        for &g in groups.iter().rev().skip(1) {
            let mut div = 100_000_000u32;
            while div > 0 {
                digits.push(((g / div) % 10) as u8);
                div /= 10;
            }
        }
        digits
    }
}

/// Divides `limbs` (little-endian) by `d` in place; returns the limbs (for
/// chaining) and the remainder.
fn divmod_small(limbs: &mut [u32], d: u32) -> (&mut [u32], u32) {
    let mut rem = 0u64;
    for limb in limbs.iter_mut().rev() {
        let cur = (rem << 32) | *limb as u64;
        *limb = (cur / d as u64) as u32;
        rem = cur % d as u64;
    }
    (limbs, rem as u32)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn integral_branch() {
        assert_eq!(format_json_number(1.0), "1");
        assert_eq!(format_json_number(100.0), "100");
        assert_eq!(format_json_number(-60.0), "-60");
        assert_eq!(format_json_number(-0.0), "0");
        assert_eq!(format_json_number(123456789.0), "123456789");
        // Above the ±9.2e18 gate: %.8g takes over.
        assert_eq!(format_json_number(9.3e18), "9.3e+18");
        assert_eq!(format_json_number(1e20), "1e+20");
    }

    #[test]
    fn g_basics() {
        assert_eq!(format_g(0.1), "0.1");
        assert_eq!(format_g(1.5), "1.5");
        assert_eq!(format_g(-7.1902902), "-7.1902902");
        assert_eq!(format_g(1e-5), "1e-05"); // %g switches to %e below 1e-4
        assert_eq!(format_g(0.0001), "0.0001");
        assert_eq!(format_g(1e8), "1e+08"); // %e at exponent >= precision
        assert_eq!(format_g(99999999.0), "99999999"); // X=7 < 8 → %f style
        assert_eq!(format_g(1e7), "10000000");
        assert_eq!(format_g(123456789.5), "1.2345679e+08");
        assert_eq!(format_g(-1e-300), "-1e-300");
        assert_eq!(format_g(f64::INFINITY), "inf");
        assert_eq!(format_g(f64::NEG_INFINITY), "-inf");
    }

    #[test]
    fn g_rounding() {
        // 9 significant digits round to 8.
        assert_eq!(format_g(0.123456789), "0.12345679");
        // Exact-tie half-to-even: …2|5 exactly → stays even.
        assert_eq!(format_g(98765432.5), "98765432");
        // …3|5 exactly → rounds up to even.
        assert_eq!(format_g(98765433.5), "98765434");
        // Carry through nines bumps the exponent to -4; %g then uses %f
        // style (the -4 boundary is inclusive), giving "0.0001" — verified
        // against the C reference vector table.
        assert_eq!(format_g(9.999999995e-5), "0.0001");
    }

    #[test]
    fn g_extremes() {
        assert_eq!(format_g(5e-324), "4.9406565e-324");
        assert_eq!(format_g(f64::MIN_POSITIVE), "2.2250739e-308");
        assert_eq!(format_g(f64::MAX), "1.7976931e+308");
        assert_eq!(format_g(1e-4 * 0.999999), "9.99999e-05");
    }
}
