#!/usr/bin/env python3
"""Generate `src/psy/frozen.rs` from the psychoacoustic oracle dumps.

Run from the crate root (`crates/musicpack-musepack-encoder`):

    python3 tools/gen_psy_tables.py

The dumps are produced by `tools/extract_psy_oracle.c` (`tables` and `bases`
modes); see
`tests/data/psy/README.md`. Nothing here talks to the reference at run time.
Run `cargo fmt` after generating.
"""
import re
import sys

DATA = "tests/data/psy"
OUT = "src/psy/frozen.rs"

CONFIGS = [
    # The original seven oracle configurations (Phase 15F), unchanged and
    # listed first so their emitted sections keep their historical order.
    ("q4-44100", "Q4_44100"),
    ("q5-44100", "Q5_44100"),
    ("q6-44100", "Q6_44100"),
    ("q7-44100", "Q7_44100"),
    ("q5-48000", "Q5_48000"),
    ("q5-37800", "Q5_37800"),
    ("q5-32000", "Q5_32000"),
    # Encoder-parity slice J.1: the remaining integer quality x sample-rate
    # combinations of the reference mpcenc (integer quality 0..=10 at all four
    # SV8 rates = 44 configurations total).
    ("q0-44100", "Q0_44100"),
    ("q0-48000", "Q0_48000"),
    ("q0-37800", "Q0_37800"),
    ("q0-32000", "Q0_32000"),
    ("q1-44100", "Q1_44100"),
    ("q1-48000", "Q1_48000"),
    ("q1-37800", "Q1_37800"),
    ("q1-32000", "Q1_32000"),
    ("q2-44100", "Q2_44100"),
    ("q2-48000", "Q2_48000"),
    ("q2-37800", "Q2_37800"),
    ("q2-32000", "Q2_32000"),
    ("q3-44100", "Q3_44100"),
    ("q3-48000", "Q3_48000"),
    ("q3-37800", "Q3_37800"),
    ("q3-32000", "Q3_32000"),
    ("q4-48000", "Q4_48000"),
    ("q4-37800", "Q4_37800"),
    ("q4-32000", "Q4_32000"),
    ("q6-48000", "Q6_48000"),
    ("q6-37800", "Q6_37800"),
    ("q6-32000", "Q6_32000"),
    ("q7-48000", "Q7_48000"),
    ("q7-37800", "Q7_37800"),
    ("q7-32000", "Q7_32000"),
    ("q8-44100", "Q8_44100"),
    ("q8-48000", "Q8_48000"),
    ("q8-37800", "Q8_37800"),
    ("q8-32000", "Q8_32000"),
    ("q9-44100", "Q9_44100"),
    ("q9-48000", "Q9_48000"),
    ("q9-37800", "Q9_37800"),
    ("q9-32000", "Q9_32000"),
    ("q10-44100", "Q10_44100"),
    ("q10-48000", "Q10_48000"),
    ("q10-37800", "Q10_37800"),
    ("q10-32000", "Q10_32000"),
]


def parse_sections(path):
    """Return `name -> (count, [u32 bits])` and a scalars dict."""
    sections = {}
    scalars = {}
    with open(path) as fh:
        lines = [l.strip() for l in fh if l.strip()]
    i = 0
    while i < len(lines):
        parts = lines[i].split()
        name = parts[0]
        if name == "max_band":
            scalars[name] = int(parts[1])
            i += 1
        elif len(parts) == 2:
            n = int(parts[1])
            vals = [int(lines[i + 1 + j], 16) for j in range(n)]
            sections[name] = (n, vals)
            i += 1 + n
        else:
            raise SystemExit("bad line: " + lines[i])
    return sections, scalars


def emit_u32_array(out, name, vals, per_line=8, indent="    "):
    out.append(f"pub(crate) const {name}: [u32; {len(vals)}] = [\n")
    for i in range(0, len(vals), per_line):
        chunk = vals[i:i + per_line]
        out.append(indent + ", ".join(f"0x{v:08x}" for v in chunk) + ",\n")
    out.append("];\n\n")


def parse_bases():
    """Parses `psy_bases.txt` (J.2): `#` comments, `rate <int>` headers and
    `flag <n>` sections of512 sixteen-hex-digit f64 words. Returns the40
    `(rate, flag, [u64 words])` entries in file order."""
    entries = []
    lines = []
    with open(f"{DATA}/psy_bases.txt") as fh:
        for line in fh:
            s = line.strip()
            if s and not s.startswith("#"):
                lines.append(s)
    i = 0
    while i < len(lines):
        head = lines[i].split()
        if head[0] != "rate":
            raise SystemExit(f"psy_bases: expected 'rate', got {lines[i]!r}")
        rate = int(head[1])
        i += 1
        while i < len(lines) and lines[i].startswith("flag "):
            flag = int(lines[i].split()[1])
            words = [int(w, 16) for w in lines[i + 1:i + 1 + 512]]
            if len(words) != 512:
                raise SystemExit(f"psy_bases: short section flag {flag} @ {rate}")
            entries.append((rate, flag, words))
            i += 1 + 512
    if len(entries) != 40:
        raise SystemExit(f"psy_bases: expected40 entries, got {len(entries)}")
    return entries


def main():
    kernels, _ = parse_sections(f"{DATA}/kernels.txt")
    out = []
    out.append("//! Frozen psychoacoustic tables, generated by\n")
    out.append("//! `tools/extract_psy_oracle.c` from the pinned reference build and\n")
    out.append("//! transcribed by `tools/gen_psy_tables.py`. Do not edit by hand.\n")
    out.append("//!\n")
    out.append("//! Values derived from libm (`pow`, `exp`, `log10`, `cos`, `sin`, `asinh`,\n")
    out.append("//! `sqrt`) are frozen as IEEE-754 bit patterns rather than recomputed, so\n")
    out.append("//! the Rust model is independent of the host math library.\n\n")

    out.append("/// Frozen per-configuration psychoacoustic tables.\n")
    out.append("pub(crate) struct PsyTablesBits {\n")
    out.append("    pub max_band: i32,\n")
    out.append("    pub fft_ltq: [u32; 512],\n")
    out.append("    pub part_ltq: [u32; 57],\n")
    out.append("    pub inv_ltq: [u32; 57],\n")
    out.append("    pub min_val: [u32; 57],\n")
    out.append("    pub loudness: [u32; 57],\n")
    out.append("    pub sprd: [u32; 3249],\n")
    out.append("    pub scalars: [u32; 4],\n")
    out.append("}\n\n")

    emit_u32_array(out, "W_BITS", kernels["w"][1])
    emit_u32_array(out, "HANN_256_BITS", kernels["Hann_256"][1])
    emit_u32_array(out, "HANN_1024_BITS", kernels["Hann_1024"][1])
    emit_u32_array(out, "HANN_1600_BITS", kernels["Hann_1600"][1])
    emit_u32_array(out, "TABCOS_BITS", kernels["tabcos"][1])
    emit_u32_array(out, "TABATAN2_BITS", kernels["tabatan2"][1])

    for cname, rname in CONFIGS:
        sec, _ = parse_sections(f"{DATA}/psy_{cname}.txt")
        with open(f"{DATA}/psy_{cname}.txt") as fh:
            mb = int(fh.readline().split()[1])
        out.append(f"pub(crate) const PSY_{rname}: PsyTablesBits = PsyTablesBits {{\n")
        out.append(f"    max_band: {mb},\n")
        for field, key in [("fft_ltq", "fftLtq"), ("part_ltq", "partLtq"),
                           ("inv_ltq", "invLtq"), ("min_val", "MinVal"),
                           ("loudness", "Loudness"), ("sprd", "SPRD"),
                           ("scalars", "scalars")]:
            vals = sec[key][1]
            out.append(f"    {field}: [\n")
            for i in range(0, len(vals), 8):
                out.append("        " + ", ".join(f"0x{v:08x}" for v in vals[i:i + 8]) + ",\n")
            out.append("    ],\n")
        out.append("};\n\n")

    # J.2: frozen ATH base arrays (f64 words), one per (rate, EarModelFlag),
    # plus an index table mirroring the MATRIX lookup style.
    bases = parse_bases()
    out.append("/// J.2: frozen ATH base arrays — `tmp` (`f64` bits as `u64`) inside the\n")
    out.append("/// reference `Ruhehoerschwelle` after the flag roll-off subtraction and\n")
    out.append("/// before the `Ltq_max` clamp; one array per `(sample rate, EarModelFlag)`.\n")
    for rate, flag, words in bases:
        out.append(f"pub(crate) const PSY_ATH_BASE_{rate}_{flag}: [u64; 512] = [\n")
        for i in range(0, 512, 8):
            out.append("        " + ", ".join(f"0x{w:016x}" for w in words[i:i + 8]) + ",\n")
        out.append("];\n\n")
    out.append("/// `(rate f32 bits, EarModelFlag, data)` index of the frozen ATH bases.\n")
    out.append(f"pub(crate) const PSY_ATH_BASES: [(u32, u32, &[u64; 512]); {len(bases)}] = [\n")
    for rate, flag, _ in bases:
        out.append(f"    ({rate}.0f32.to_bits(), {flag}, &PSY_ATH_BASE_{rate}_{flag}),\n")
    out.append("];\n\n")

    with open(OUT, "w") as fh:
        fh.write("".join(out))
    print("wrote", OUT, "bytes", len("".join(out)))


main()
