//! Differential metadata verification against the reference libmpcdec.
//!
//! `tests/data/musepack_oracle.jsonl` is generated by
//! `tools/musepack_oracle.mjs` from the project's vendored decoder built to
//! WebAssembly. This test parses the same fixtures with the Rust SV8 layer
//! and requires the reference-exposed facts to agree exactly. The reference
//! PCM digest is committed alongside for the deferred synthesis key; it is
//! deliberately not asserted here (no PCM is produced yet).

use musicpack_core::audio::musepack::sv8;
use musicpack_core::format::checksum::sha256_hex;
use musicpack_core::json::{self, Value};

fn string(v: &Value, key: &str) -> Option<String> {
    match v.get(key) {
        Some(Value::String(s)) => Some(s.clone()),
        _ => None,
    }
}

fn number(v: &Value, key: &str) -> Option<f64> {
    match v.get(key) {
        Some(Value::Number(n)) => Some(*n),
        _ => None,
    }
}

#[test]
fn sv8_metadata_matches_the_reference_decoder() {
    let root = env!("CARGO_MANIFEST_DIR");
    let oracle = std::fs::read_to_string(format!("{root}/tests/data/musepack_oracle.jsonl"))
        .expect("committed musepack oracle");

    let mut count = 0;
    for line in oracle.lines().filter(|l| !l.trim().is_empty()) {
        let record = json::parse(line.as_bytes()).expect("oracle JSON");
        let file = string(&record, "file").expect("file");
        let path = format!("{root}/tests/fixtures/musepack/{file}");
        let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("{path}: {e}"));

        assert_eq!(
            sha256_hex(&bytes),
            string(&record, "bytesSha256").expect("bytesSha256"),
            "{file}: fixture bytes changed; regenerate the oracle"
        );

        let info = sv8::parse(&bytes).unwrap_or_else(|e| panic!("{file}: {e}"));

        // Stream facts the reference decoder exposes, asserted exactly.
        assert_eq!(
            info.stream_version as f64,
            number(&record, "streamVersion").unwrap(),
            "{file}: stream version"
        );
        assert_eq!(
            info.sample_rate as f64,
            number(&record, "sampleRate").unwrap(),
            "{file}: sample rate"
        );
        assert_eq!(
            info.channels as f64,
            number(&record, "channels").unwrap(),
            "{file}: channels"
        );
        assert_eq!(
            info.length_samples() as f64,
            number(&record, "lengthSamples").unwrap(),
            "{file}: playable length"
        );

        // Internal consistency and structural bounds (the reference's
        // `check_streaminfo`).
        assert!(info.beg_silence <= info.samples, "{file}: beg_silence");
        assert_eq!(info.samples - info.beg_silence, info.length_samples());
        assert!(
            (1..32).contains(&info.max_band),
            "{file}: max_band {}",
            info.max_band
        );
        assert!(
            info.channels == 1 || info.channels == 2,
            "{file}: channels {}",
            info.channels
        );
        assert!(info.sample_rate != 0, "{file}: sample rate");
        assert!(info.block_pwr < 32, "{file}: block_pwr");

        // PCM: decode with the Rust port and require byte-identical output
        // (SHA-256 over canonical little-endian f32).
        let mut decoder =
            musicpack_core::audio::musepack::MpcDecoder::new(bytes.clone()).expect("decoder");
        let channels = info.channels as usize;
        let mut pcm = Vec::new();
        let mut buffer = vec![0.0f32; 1152 * channels];
        loop {
            let frames = decoder.read_f32(&mut buffer).expect("decode");
            if frames == 0 {
                break;
            }
            pcm.extend_from_slice(&buffer[..frames * channels]);
        }
        let mut canonical = Vec::with_capacity(pcm.len() * 4);
        for sample in &pcm {
            canonical.extend_from_slice(&sample.to_le_bytes());
        }
        assert_eq!(
            pcm.len() / channels,
            number(&record, "pcmFrames").unwrap() as usize,
            "{file}: decoded frame count"
        );
        assert_eq!(
            sha256_hex(&canonical),
            string(&record, "pcmSha256").expect("pcmSha256"),
            "{file}: PCM mismatch"
        );

        count += 1;
    }

    assert_eq!(count, 6, "expected the six committed fixtures");
}
