//! Differential replay of the committed TypeScript player-core oracle.
//!
//! `tests/data/player_oracle.jsonl` is generated by
//! `tools/player_oracle.ts` (bundled with esbuild and run under Node; see the
//! tool header). It records the reference TypeScript behaviour for the pure
//! planner/gain/snapshot/queue logic and for scripted player scenarios driven
//! through a fake engine. This test replays each record against the Rust
//! implementation and asserts the same observable result.

use std::cell::RefCell;
use std::collections::HashMap;
use std::path::PathBuf;
use std::rc::Rc;

use musicpack_core::json::{self, Value};
use musicpack_core::player::engine::{
    CrossfadeResult, CrossfadeStart, Engine, EngineCapabilities, EngineResult,
};
use musicpack_core::player::events::PlayerEvent;
use musicpack_core::player::player::{Player, PlayerOptions, PlayerPorts, PlayerState};
use musicpack_core::player::queue::QueueModel;
use musicpack_core::player::snapshot::decode_snapshot;
use musicpack_core::player::transition::{
    BoundaryProfile, TransitionPlan, TransitionQuery, plan_transition,
};
use musicpack_core::player::types::{
    EngineKind, PlaybackItem, PlaybackSource, RepeatMode, SourceKind, StreamInfo,
};
use musicpack_core::player::{combined_gain, db_to_linear, normalization_gain};

const RATE: u32 = 44_100;

fn s<'a>(v: &'a Value, k: &str) -> Option<&'a str> {
    match v.get(k) {
        Some(Value::String(x)) => Some(x.as_str()),
        _ => None,
    }
}
fn num(v: &Value, k: &str) -> Option<f64> {
    match v.get(k) {
        Some(Value::Number(x)) => Some(*x),
        _ => None,
    }
}
fn bool_at(v: &Value, k: &str) -> Option<bool> {
    match v.get(k) {
        Some(Value::Bool(x)) => Some(*x),
        _ => None,
    }
}
fn arr<'a>(v: &'a Value, k: &str) -> Option<&'a [Value]> {
    match v.get(k) {
        Some(Value::Array(a)) => Some(a.as_slice()),
        _ => None,
    }
}

fn item(n: i64) -> PlaybackItem {
    PlaybackItem {
        id: format!("t{n}"),
        track_id: n,
        source: PlaybackSource {
            kind: SourceKind::HttpRange,
            url: format!("/api/v1/tracks/{n}/audio"),
            byte_size: Some(100),
        },
        duration_hint_seconds: None,
        title: format!("T{n}"),
        artist: "A".into(),
        album_title: "AL".into(),
        edition: None,
        artwork_url: None,
        loudness: None,
        album_loudness: None,
        codec: Some("musepack-sv8".into()),
        mime_type: None,
        extra: Vec::new(),
    }
}

fn profile_from(v: Option<&Value>) -> Option<BoundaryProfile> {
    let v = v?;
    if matches!(v, Value::Null) {
        return None;
    }
    let tail = arr(v, "tail").map(|a| a.iter().filter_map(value_f64).collect());
    let head = arr(v, "head").map(|a| a.iter().filter_map(value_f64).collect());
    Some(BoundaryProfile {
        length_seconds: num(v, "lengthSeconds").unwrap_or(0.0),
        tail,
        head,
    })
}

fn value_f64(v: &Value) -> Option<f64> {
    match v {
        Value::Number(n) => Some(*n),
        _ => None,
    }
}

fn plan_from(v: &Value) -> TransitionPlan {
    match s(v, "type") {
        Some("gapless") => TransitionPlan::Gapless,
        Some("hard-cut") => TransitionPlan::HardCut,
        _ => TransitionPlan::SweetFade {
            overlap_seconds: num(v, "overlapSeconds").unwrap_or(0.0),
        },
    }
}

fn compare_plan(a: TransitionPlan, b: TransitionPlan, ctx: &str) {
    match (a, b) {
        (TransitionPlan::Gapless, TransitionPlan::Gapless)
        | (TransitionPlan::HardCut, TransitionPlan::HardCut) => {}
        (
            TransitionPlan::SweetFade { overlap_seconds: x },
            TransitionPlan::SweetFade { overlap_seconds: y },
        ) => assert!((x - y).abs() < 1e-9, "{ctx}: sweet-fade {x} vs {y}"),
        (x, y) => panic!("{ctx}: plan mismatch {x:?} vs {y:?}"),
    }
}

fn check_transition(v: &Value) {
    let id = s(v, "id").unwrap();
    let spb = num(v, "secondsPerBucket").unwrap();
    let query = v.get("query").unwrap();
    let query = TransitionQuery {
        outgoing: item(1),
        incoming: item(2),
        max_fade_seconds: num(query, "maxFadeSeconds").unwrap(),
        repeat_one: bool_at(query, "repeatOne").unwrap_or(false),
        same_release: bool_at(query, "sameRelease"),
    };
    let outgoing = profile_from(v.get("outgoing"));
    let incoming = profile_from(v.get("incoming"));
    let got = plan_transition(&query, outgoing.as_ref(), incoming.as_ref(), spb);
    compare_plan(got, plan_from(v.get("plan").unwrap()), id);
}

fn check_gain(v: &Value) {
    let id = s(v, "id").unwrap();
    let mode = s(v, "mode").unwrap();
    let mode = match mode {
        "off" => musicpack_core::player::types::NormalizationMode::Off,
        "track" => musicpack_core::player::types::NormalizationMode::Track,
        _ => musicpack_core::player::types::NormalizationMode::Album,
    };
    let track = v.get("track").and_then(|t| {
        if matches!(t, Value::Null) {
            None
        } else {
            Some(musicpack_core::player::types::TrackLoudness {
                lufs: num(t, "lufs")?,
                true_peak_db: num(t, "truePeakDb")?,
            })
        }
    });
    let album = v.get("album").and_then(|a| {
        if matches!(a, Value::Null) {
            None
        } else {
            Some(musicpack_core::player::types::AlbumLoudness {
                album_lufs: num(a, "albumLufs")?,
                album_true_peak_db: num(a, "albumTruePeakDb")?,
            })
        }
    });
    let want = num(v, "gain").unwrap();
    let got = normalization_gain(mode, track.as_ref(), album.as_ref());
    assert!((got - want).abs() < 1e-9, "{id}: gain {got} vs {want}");
}

fn check_snapshot(v: &Value) {
    let id = s(v, "id").unwrap();
    let raw = s(v, "raw").unwrap();
    let decoded = decode_snapshot(raw);
    let want = v.get("decoded").unwrap();
    if matches!(want, Value::Null) {
        assert!(decoded.is_none(), "{id}: expected decode failure");
        return;
    }
    let got = decoded.unwrap_or_else(|| panic!("{id}: expected decode"));
    assert_eq!(got.v as f64, num(want, "v").unwrap(), "{id}: v");
    assert_eq!(got.index, num(want, "index").unwrap() as i64, "{id}: index");
    assert!(
        (got.position_seconds - num(want, "positionSeconds").unwrap()).abs() < 1e-9,
        "{id}: position"
    );
    let want_volume = num(want, "volume");
    assert_eq!(got.volume, want_volume, "{id}: volume");
    let want_mode =
        s(want, "normalizeMode").map(musicpack_core::player::types::NormalizationMode::parse);
    assert_eq!(got.normalize_mode, want_mode, "{id}: normalize");
    assert_eq!(
        got.repeat.as_str(),
        s(want, "repeat").unwrap(),
        "{id}: repeat"
    );
    assert_eq!(
        got.shuffle,
        bool_at(want, "shuffle").unwrap(),
        "{id}: shuffle"
    );
    assert!(
        (got.crossfade_seconds - num(want, "crossfadeSeconds").unwrap()).abs() < 1e-9,
        "{id}: crossfade"
    );
    let want_ids: Vec<Option<String>> = arr(want, "itemIds")
        .unwrap()
        .iter()
        .map(|x| match x {
            Value::String(s) => Some(s.clone()),
            _ => None,
        })
        .collect();
    let got_ids: Vec<Option<String>> = got
        .items
        .iter()
        .map(|it| s(it, "id").map(str::to_string))
        .collect();
    assert_eq!(got_ids, want_ids, "{id}: item ids");
}

fn check_queue(v: &Value) {
    let id = s(v, "id").unwrap();
    let mut q = QueueModel::new(Box::new(|| 0.5));
    q.play_sequence((1..=4).map(item).collect(), 0).unwrap();
    if bool_at(v, "shuffle").unwrap_or(false) {
        q.set_shuffle(true);
    }
    q.set_repeat(RepeatMode::parse(s(v, "repeat").unwrap()));
    for op in arr(v, "ops").unwrap() {
        let op = match op {
            Value::Array(a) => a,
            _ => panic!("{id}: op must be an array"),
        };
        let name = match &op[0] {
            Value::String(x) => Some(x.as_str()),
            _ => None,
        };
        let a = op.get(1).and_then(value_f64).unwrap_or(0.0) as i64;
        let b = op.get(2).and_then(value_f64).unwrap_or(0.0) as i64;
        match name.unwrap() {
            "next" => {
                q.next();
            }
            "previous" => {
                q.previous();
            }
            "moveTo" => q.move_to(a),
            "move" => q.move_item(a, b),
            "removeAt" => q.remove_at(a),
            "playNext" => q.play_next(item(a)),
            "clear" => q.clear(),
            other => panic!("{id}: unknown op {other}"),
        }
    }
    let finalv = v.get("final").unwrap();
    let want_items: Vec<String> = arr(finalv, "items")
        .unwrap()
        .iter()
        .map(|x| match x {
            Value::String(s) => s.clone(),
            _ => panic!("{id}: item id must be a string"),
        })
        .collect();
    let got_items: Vec<String> = q.items().iter().map(|i| i.id.clone()).collect();
    assert_eq!(got_items, want_items, "{id}: items");
    assert_eq!(
        q.index(),
        num(finalv, "index").unwrap() as i64,
        "{id}: index"
    );
    assert_eq!(
        q.repeat().as_str(),
        s(finalv, "repeat").unwrap(),
        "{id}: repeat"
    );
    assert_eq!(
        q.shuffling(),
        bool_at(finalv, "shuffle").unwrap(),
        "{id}: shuffle"
    );
}

// ---- scenario engine ------------------------------------------------------

struct St {
    crossfade: bool,
    fade_mode: u8, // 0 null, 1 immediate, 2 deferred
    mismatch: bool,
    default_len: u64,
    hints: HashMap<i64, u64>,
    overlap_frames: u64,
    plan: TransitionPlan,
    rendered: u64,
    opened: Vec<String>,
    prepared: Vec<String>,
    begin: Vec<(String, f64)>,
    seeks: Vec<u64>,
    standby: Option<PlaybackItem>,
    standby_info: Option<StreamInfo>,
}

fn length_for(st: &St, it: &PlaybackItem) -> u64 {
    if let Some(hint) = it.duration_hint_seconds {
        if hint.is_finite() && hint > 0.0 {
            return (hint * RATE as f64) as u64;
        }
    }
    st.hints
        .get(&it.track_id)
        .copied()
        .unwrap_or(st.default_len)
}

struct FakeEngine {
    st: Rc<RefCell<St>>,
}

impl FakeEngine {
    fn info(&self, it: &PlaybackItem) -> StreamInfo {
        StreamInfo {
            rate: RATE,
            channels: 2,
            version: 0,
            length_samples: length_for(&self.st.borrow(), it),
        }
    }
}

impl Engine for FakeEngine {
    fn capabilities(&self) -> EngineCapabilities {
        EngineCapabilities {
            preload_next: true,
            sample_accurate_gapless: true,
            decode_gate: true,
            crossfade: self.st.borrow().crossfade,
        }
    }
    fn open(&mut self, item: &PlaybackItem) -> EngineResult<StreamInfo> {
        let info = self.info(item);
        let mut st = self.st.borrow_mut();
        st.opened.push(item.source.url.clone());
        st.rendered = 0;
        Ok(info)
    }
    fn play(&mut self) -> EngineResult<()> {
        Ok(())
    }
    fn pause(&mut self) {}
    fn seek(&mut self, samples: u64) {
        let mut st = self.st.borrow_mut();
        st.seeks.push(samples);
        st.rendered = 0;
    }
    fn set_gain(&mut self, _linear: f64) {}
    fn rendered_samples(&self) -> u64 {
        self.st.borrow().rendered
    }
    fn close(&mut self) {}
    fn prepare_next(&mut self, item: &PlaybackItem) -> Option<StreamInfo> {
        let info = self.info(item);
        let mut st = self.st.borrow_mut();
        st.prepared.push(item.source.url.clone());
        st.standby = Some(item.clone());
        st.standby_info = Some(info);
        Some(info)
    }
    fn advance(&mut self, expected: Option<&PlaybackItem>) -> Option<StreamInfo> {
        let mut st = self.st.borrow_mut();
        let (Some(expected), Some(standby)) = (expected, st.standby.as_ref()) else {
            return None;
        };
        if !musicpack_core::player::types::same_item_identity(expected, standby) {
            return None;
        }
        st.standby = None;
        st.standby_info.take()
    }
    fn begin_crossfade(&mut self, next: &PlaybackItem, fade_seconds: f64) -> CrossfadeStart {
        let mut st = self.st.borrow_mut();
        st.begin.push((next.id.clone(), fade_seconds));
        if st.mismatch || st.fade_mode == 0 {
            return CrossfadeStart::Declined;
        }
        let info = StreamInfo {
            rate: RATE,
            channels: 2,
            version: 0,
            length_samples: length_for(&st, next),
        };
        if st.fade_mode == 2 {
            return CrossfadeStart::Pending;
        }
        CrossfadeStart::Completed(CrossfadeResult {
            info,
            overlap_frames: st.overlap_frames,
        })
    }
}

fn state_str(state: PlayerState) -> &'static str {
    match state {
        PlayerState::Idle => "idle",
        PlayerState::Loading => "loading",
        PlayerState::Buffering => "buffering",
        PlayerState::Playing => "playing",
        PlayerState::Paused => "paused",
        PlayerState::Ended => "ended",
        PlayerState::Error => "error",
        _ => "unknown",
    }
}

fn scenario_engine_config(
    v: &Value,
) -> (bool, u8, bool, u64, HashMap<i64, u64>, u64, TransitionPlan) {
    let crossfade = bool_at(v, "crossfade").unwrap_or(false);
    let fade_mode = match s(v, "fade").unwrap_or("null") {
        "immediate" => 1,
        "deferred" => 2,
        _ => 0,
    };
    let mismatch = bool_at(v, "standbyMismatch").unwrap_or(false);
    let default_len = (num(v, "defaultSeconds").unwrap_or(10.0) * RATE as f64) as u64;
    let mut hints = HashMap::new();
    if let Some(Value::Object(members)) = v.get("hints") {
        for (k, val) in members {
            if let (Ok(id), Some(secs)) = (k.parse::<i64>(), value_f64(val)) {
                hints.insert(id, (secs * RATE as f64) as u64);
            }
        }
    }
    let overlap_frames = num(v, "overlapFrames").unwrap_or(0.0) as u64;
    let plan = match v.get("plan") {
        Some(Value::String(p)) if p == "gapless" => TransitionPlan::Gapless,
        Some(Value::String(p)) if p == "hard-cut" => TransitionPlan::HardCut,
        Some(Value::Object(_)) => TransitionPlan::SweetFade {
            overlap_seconds: num(v.get("plan").unwrap(), "sweet").unwrap_or(0.0),
        },
        _ => TransitionPlan::SweetFade {
            overlap_seconds: f64::NAN,
        },
    };
    (
        crossfade,
        fade_mode,
        mismatch,
        default_len,
        hints,
        overlap_frames,
        plan,
    )
}

fn check_scenario(v: &Value) {
    let id = s(v, "id").unwrap();
    let engine_cfg = v.get("engine").unwrap();
    let (crossfade, fade_mode, mismatch, default_len, hints, overlap_frames, plan) =
        scenario_engine_config(engine_cfg);
    let plan_present = !matches!(v.get("plan"), Some(Value::Null))
        && !matches!(engine_cfg.get("plan"), None | Some(Value::String(_)))
        || s(engine_cfg, "plan").map(|p| p != "none").unwrap_or(false);
    let plan_value = plan;
    let use_plan = match engine_cfg.get("plan") {
        Some(Value::String(p)) => p != "none",
        Some(Value::Object(_)) => true,
        _ => false,
    };
    let _ = plan_present;

    let st = Rc::new(RefCell::new(St {
        crossfade,
        fade_mode,
        mismatch,
        default_len,
        hints,
        overlap_frames,
        plan: plan_value,
        rendered: 0,
        opened: Vec::new(),
        prepared: Vec::new(),
        begin: Vec::new(),
        seeks: Vec::new(),
        standby: None,
        standby_info: None,
    }));
    let factory_st = st.clone();
    let plan_st = st.clone();
    let plan_hint = use_plan;
    let ports = PlayerPorts {
        engine_factory: Box::new(move |_kind: EngineKind| {
            Box::new(FakeEngine {
                st: factory_st.clone(),
            }) as Box<dyn Engine>
        }),
        resolve_kind: Box::new(|_i: &PlaybackItem| Ok(EngineKind::Musepack)),
        plan_transition: if plan_hint {
            Some(Box::new(move |_q: &TransitionQuery| plan_st.borrow().plan))
        } else {
            None
        },
    };
    let mut player = Player::new(
        QueueModel::new(Box::new(|| 0.5)),
        ports,
        PlayerOptions::default(),
    );

    let mut drift = false;
    let mut all_events: Vec<PlayerEvent> = Vec::new();
    for action in arr(v, "actions").unwrap() {
        let action = match action {
            Value::String(a) => a.clone(),
            _ => panic!("{id}: action must be a string"),
        };
        let (op, arg) = action.split_once(':').unwrap_or((action.as_str(), ""));
        match op {
            "play_seq" => {
                let (list, start) = arg.split_once(';').unwrap_or((arg, "0"));
                let items: Vec<PlaybackItem> = list
                    .split(',')
                    .map(|n| {
                        let n: i64 = n.parse().unwrap();
                        let mut it = item(n);
                        if let Some(secs) = st.borrow().hints.get(&n) {
                            it.duration_hint_seconds = Some(*secs as f64 / RATE as f64);
                        }
                        it
                    })
                    .collect();
                all_events.extend(player.play_sequence(items, start.parse().unwrap()));
                all_events.extend(player.on_primed());
            }
            "prime" => all_events.extend(player.on_primed()),
            "tick" => all_events.extend(player.on_tick()),
            "eos" => all_events.extend(player.on_eos()),
            "pause" => all_events.extend(player.pause()),
            "next" => {
                all_events.extend(player.next());
                all_events.extend(player.on_primed());
            }
            "previous" => {
                all_events.extend(player.previous());
                all_events.extend(player.on_primed());
            }
            "seek" => {
                all_events.extend(player.seek(arg.parse().unwrap()));
                all_events.extend(player.on_primed());
            }
            "teardown" => all_events.extend(player.teardown()),
            "set_repeat" => {
                all_events.extend(player.set_repeat(RepeatMode::parse(arg)));
            }
            "set_shuffle" => {
                all_events.extend(player.set_shuffle(arg == "true"));
            }
            "set_order" => {
                let order: Vec<usize> = arg.split(',').map(|n| n.parse().unwrap()).collect();
                player.queue_mut().set_presentation_order_for_test(order);
            }
            "set_crossfade" => {
                all_events.extend(player.set_crossfade(arg.parse().unwrap()));
            }
            "set_rendered" => {
                st.borrow_mut().rendered = arg.parse().unwrap();
            }
            "queue_remove" => {
                player.queue_mut().remove_at(arg.parse().unwrap());
            }
            "queue_changed" => {
                all_events.extend(player.on_queue_changed());
            }
            "resolve_fade" => {
                let target = item(2);
                let info = StreamInfo {
                    rate: RATE,
                    channels: 2,
                    version: 0,
                    length_samples: length_for(&st.borrow(), &target),
                };
                all_events.extend(player.on_crossfade_complete(Some(CrossfadeResult {
                    info,
                    overlap_frames: 0,
                })));
            }
            other => panic!("{id}: unknown action {other}"),
        }
    }
    for ev in &all_events {
        if matches!(ev, PlayerEvent::BoundaryDrift { .. }) {
            drift = true;
        }
    }

    let want = v.get("final").unwrap();
    let got = player.model();
    assert_eq!(
        state_str(got.state),
        s(want, "state").unwrap(),
        "{id}: state"
    );
    assert_eq!(
        player.queue().index(),
        num(want, "index").unwrap() as i64,
        "{id}: index"
    );
    assert_eq!(
        got.current.as_ref().map(|i| i.id.clone()),
        s(want, "currentId").map(str::to_string),
        "{id}: current"
    );
    let want_pos = num(want, "positionSeconds").unwrap();
    assert!(
        (got.position_seconds - want_pos).abs() < 1e-3,
        "{id}: position {} vs {want_pos}",
        got.position_seconds
    );
    let want_dur = num(want, "durationSeconds").unwrap();
    assert!(
        (got.duration_seconds - want_dur).abs() < 1e-3,
        "{id}: duration {} vs {want_dur}",
        got.duration_seconds
    );
    let want_opened: Vec<String> = arr(want, "opened")
        .unwrap()
        .iter()
        .map(|x| match x {
            Value::String(s) => s.clone(),
            _ => panic!("{id}: opened entry"),
        })
        .collect();
    let got_opened: Vec<String> = st.borrow().opened.clone();
    assert_eq!(got_opened, want_opened, "{id}: opened");
    let want_prepared: Vec<String> = arr(want, "prepared")
        .unwrap()
        .iter()
        .map(|x| match x {
            Value::String(s) => s.clone(),
            _ => panic!("{id}: prepared entry"),
        })
        .collect();
    let got_prepared: Vec<String> = st.borrow().prepared.clone();
    assert_eq!(got_prepared, want_prepared, "{id}: prepared");
    let want_calls: Vec<(String, f64)> = arr(want, "beginCrossfade")
        .unwrap()
        .iter()
        .map(|pair| {
            let pair = match pair {
                Value::Array(a) => a,
                _ => panic!("{id}: beginCrossfade entry"),
            };
            (
                match &pair[0] {
                    Value::String(x) => x.clone(),
                    _ => panic!("{id}: crossfade target"),
                },
                value_f64(&pair[1]).unwrap(),
            )
        })
        .collect();
    let got_calls: Vec<(String, f64)> = st.borrow().begin.clone();
    assert_eq!(got_calls.len(), want_calls.len(), "{id}: crossfade calls");
    for (a, b) in got_calls.iter().zip(want_calls.iter()) {
        assert_eq!(a.0, b.0, "{id}: crossfade target");
        assert!(
            (a.1 - b.1).abs() < 1e-9,
            "{id}: crossfade secs {} vs {}",
            a.1,
            b.1
        );
    }
    assert_eq!(
        st.borrow().seeks.len(),
        arr(want, "seekCalls").unwrap().len(),
        "{id}: seek count"
    );
    for (got, want) in st
        .borrow()
        .seeks
        .iter()
        .zip(arr(want, "seekCalls").unwrap().iter())
    {
        assert_eq!(*got, value_f64(want).unwrap() as u64, "{id}: seek");
    }
    assert_eq!(drift, bool_at(want, "drift").unwrap(), "{id}: drift");
}

#[test]
fn replays_the_typescript_player_oracle() {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/data/player_oracle.jsonl");
    let text = std::fs::read_to_string(&path).expect("committed player oracle");
    let mut counts = (0usize, 0usize, 0usize, 0usize);
    for (line_no, line) in text.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let v = json::parse(line.as_bytes())
            .unwrap_or_else(|e| panic!("oracle line {}: {e}", line_no + 1));
        match s(&v, "kind") {
            Some("transition") => {
                check_transition(&v);
                counts.0 += 1;
            }
            Some("gain") => {
                check_gain(&v);
                counts.1 += 1;
            }
            Some("db-to-linear") => {
                let got = db_to_linear(num(&v, "db").unwrap());
                assert!((got - num(&v, "linear").unwrap()).abs() < 1e-9);
                counts.1 += 1;
            }
            Some("combined-gain") => {
                let got = combined_gain(num(&v, "volume").unwrap(), num(&v, "normDb").unwrap());
                assert!((got - num(&v, "gain").unwrap()).abs() < 1e-9);
                counts.1 += 1;
            }
            Some("snapshot") => {
                check_snapshot(&v);
                counts.2 += 1;
            }
            Some("queue") => {
                check_queue(&v);
                counts.2 += 1;
            }
            Some("scenario") => {
                check_scenario(&v);
                counts.3 += 1;
            }
            other => panic!("unknown oracle kind {other:?}"),
        }
    }
    assert!(counts.0 >= 9, "transition cases");
    assert!(counts.1 >= 10, "gain cases");
    assert!(counts.2 >= 13, "snapshot+queue cases");
    assert!(counts.3 >= 15, "player scenarios");
}
