//! Differential replay of the representation-selection oracle.
//!
//! `tests/data/policy_oracle.jsonl` is generated by `tools/policy_oracle.ts`,
//! which drives the REAL Phase 4 TypeScript resolver
//! (`web/app/src/lib/state/representation-selection.ts`). This test recreates
//! the same inputs, parses the preference with the Rust port, resolves with
//! the Rust policy, and requires the same selection and the same normalized
//! preference.

use musicpack_core::json::{self, Value};
use musicpack_core::policy::{
    AudioPreference, Candidate, Playability, RepresentationRef, SourceRef, TrackAudio,
    resolve_audio,
};

fn string(v: &Value, key: &str) -> Option<String> {
    match v.get(key) {
        Some(Value::String(s)) => Some(s.clone()),
        _ => None,
    }
}

fn number(v: &Value, key: &str) -> Option<f64> {
    match v.get(key) {
        Some(Value::Number(n)) => Some(*n),
        _ => None,
    }
}

fn string_array(v: &Value, key: &str) -> Option<Vec<String>> {
    match v.get(key) {
        Some(Value::Array(items)) => Some(
            items
                .iter()
                .filter_map(|item| match item {
                    Value::String(s) => Some(s.clone()),
                    _ => None,
                })
                .collect(),
        ),
        _ => None,
    }
}

fn number_array(v: &Value, key: &str) -> Vec<f64> {
    match v.get(key) {
        Some(Value::Array(items)) => items
            .iter()
            .filter_map(|item| match item {
                Value::Number(n) => Some(*n),
                _ => None,
            })
            .collect(),
        _ => Vec::new(),
    }
}

fn track_from_value(track: &Value) -> TrackAudio {
    let reps = match track.get("reps") {
        Some(Value::Array(items)) => items
            .iter()
            .map(|r| RepresentationRef {
                id: number(r, "id").expect("rep id"),
                codec: string(r, "codec"),
                mime_type: string(r, "mimeType"),
            })
            .collect(),
        _ => Vec::new(),
    };
    TrackAudio {
        codec: string(track, "codec"),
        mime_type: string(track, "mimeType"),
        representations: reps,
    }
}

struct Spec {
    codecs: Option<Vec<String>>,
    reject_mimes: Vec<String>,
    reject_ids: Vec<f64>,
}

impl Playability for Spec {
    fn can_play(&self, candidate: &Candidate<'_>) -> bool {
        if let SourceRef::Representation { id } = candidate.source {
            if self.reject_ids.contains(&id) {
                return false;
            }
        }
        let mime = candidate.mime_type.unwrap_or("").to_lowercase();
        if self.reject_mimes.contains(&mime) {
            return false;
        }
        match &self.codecs {
            Some(codecs) => {
                let codec = candidate.codec.unwrap_or("").to_lowercase();
                codecs.contains(&codec)
            }
            None => true,
        }
    }
}

fn replay(record: &Value) {
    let id = match record.get("id") {
        Some(Value::String(s)) => s.clone(),
        _ => String::from("<no id>"),
    };
    let track_value = record.get("track").expect("track");
    let track = track_from_value(track_value);

    let predicate = record.get("predicate").expect("predicate");
    let spec = Spec {
        codecs: string_array(predicate, "codecs").map(|mut c| {
            c.iter_mut().for_each(|s| *s = s.to_lowercase());
            c
        }),
        reject_mimes: string_array(predicate, "rejectMimes")
            .unwrap_or_default()
            .iter()
            .map(|s| s.to_lowercase())
            .collect(),
        reject_ids: number_array(predicate, "rejectIds"),
    };

    // Preference: a missing `pref` and a JSON `null` both mean "undefined".
    let pref = record.get("pref").and_then(AudioPreference::from_value);
    let expected_pref = match record.get("prefParsed") {
        Some(Value::Null) | None => None,
        Some(v) => AudioPreference::from_value(v),
    };
    assert_eq!(pref, expected_pref, "{id}: parsed preference");

    let selected = resolve_audio(&track, pref.as_ref(), &spec);
    let got = selected.representation_id(&track);
    let expected = match record.get("expected").and_then(|e| e.get("representation")) {
        Some(Value::Number(n)) => Some(*n),
        _ => None,
    };
    assert_eq!(got, expected, "{id}: selected representation");
}

#[test]
fn replays_the_typescript_representation_policy() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/data/policy_oracle.jsonl"
    );
    let text = std::fs::read_to_string(path).expect("committed policy oracle");
    let mut count = 0;
    for line in text.lines().filter(|l| !l.trim().is_empty()) {
        let record = json::parse(line.as_bytes()).expect("oracle JSON");
        replay(&record);
        count += 1;
    }
    assert!(count >= 30, "expected a broad policy corpus, got {count}");
}
