#!/usr/bin/env node
// Copyright (c) 2026, The MusicPack Development Team
// SPDX-License-Identifier: BSD-3-Clause

// WASM build pipeline — the replacement for the legacy `sync-wasm.sh`.
//
//   crates/musicpack-wasm (source of truth, this repository)
//     ↓  cargo build --release --target wasm32-unknown-unknown
//     ↓  wasm-bindgen --target no-modules
//   web/app/public/rust/musicpack_wasm.{js,wasm}   (gitignored artifacts)
//     ↓  vite dev / vite build (serves public/ verbatim)
//   Web application
//
// Behavior:
//   * rebuilds only when a crate source is newer than the generated
//     artifacts (mtime walk over crates/{musicpack-core,musicpack-engine,
//     musicpack-wasm}), so stale artifacts cannot survive a source change;
//   * `--force` rebuilds unconditionally, `--check` fails loudly when
//     artifacts are missing/stale without rebuilding (CI pre-flight);
//   * the legacy Emscripten decoder (public/musepack.*) is NOT built here:
//     it is a committed frozen artifact of the immutable oracle — see
//     app/public/PROVENANCE-legacy-decoder.md.

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const webRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = resolve(webRoot, '..');
const outDir = join(webRoot, 'app', 'public', 'rust');
const glue = join(outDir, 'musicpack_wasm.js');
const binary = join(outDir, 'musicpack_wasm_bg.wasm');
const wasmSource = join(
  repoRoot,
  'target',
  'wasm32-unknown-unknown',
  'release',
  'musicpack_wasm.wasm',
);
const CRATE_SOURCES = [
  'crates/musicpack-wasm',
  'crates/musicpack-engine',
  'crates/musicpack-core/src',
  'crates/musicpack-core/Cargo.toml',
  'crates/musicpack-engine/Cargo.toml',
  'crates/musicpack-wasm/Cargo.toml',
  'Cargo.lock',
].map((p) => join(repoRoot, p));

const force = process.argv.includes('--force');
const check = process.argv.includes('--check');

function newestSourceMtime(paths, acc = { t: 0, file: '' }) {
  for (const p of paths) {
    if (!existsSync(p)) continue;
    const st = statSync(p);
    if (st.isFile() && st.mtimeMs > acc.t) acc = { t: st.mtimeMs, file: p };
    if (st.isDirectory()) newestSourceMtime(readdirSync(p).map((f) => join(p, f)), acc);
  }
  return acc;
}

function artifactStale() {
  if (!existsSync(glue) || !existsSync(binary)) return { stale: true, why: 'artifacts missing' };
  const newest = newestSourceMtime(CRATE_SOURCES);
  const built = statSync(binary).mtimeMs;
  if (newest.t > built) return { stale: true, why: `source changed: ${newest.file}` };
  if (!existsSync(wasmSource) || statSync(wasmSource).mtimeMs > built) {
    return { stale: true, why: 'intermediate cargo artifact newer than binding' };
  }
  return { stale: false, why: '' };
}

const state = artifactStale();
if (!state.stale && !force) {
  console.log('wasm: binding up to date (rust sources unchanged since last build)');
  process.exit(0);
}
if (check && state.stale) {
  console.error(`wasm: binding missing or stale (${state.why}); run: node scripts/build-wasm.mjs`);
  process.exit(1);
}

console.log(`wasm: building Rust binding (${force ? 'forced' : state.why})`);
const run = (cmd, args, opts = {}) =>
  execFileSync(cmd, args, { stdio: 'inherit', cwd: repoRoot, ...opts });

run('cargo', [
  'build',
  '-p',
  'musicpack-wasm',
  '--target',
  'wasm32-unknown-unknown',
  '--release',
]);
try {
  run('wasm-bindgen', ['--version']);
} catch {
  console.error(
    'wasm: wasm-bindgen CLI not found. Install the version matching the\n' +
      'crate dependency (see crates/musicpack-wasm/README.md), e.g.:\n' +
      '  cargo install wasm-bindgen-cli --version 0.2.128',
  );
  process.exit(1);
}
mkdirSync(outDir, { recursive: true });
run('wasm-bindgen', [
  '--target',
  'no-modules',
  '--out-dir',
  outDir,
  '--out-name',
  'musicpack_wasm',
  wasmSource,
]);
console.log(`wasm: wrote ${glue}`);

// The no-modules glue binds `wasm_bindgen` as a top-level `let` — a global
// *lexical* binding that CSP-compliant app code cannot reach (inline
// scripts and eval are both blocked by the app CSP; only script-src 'self'
// files may run). This tiny generated classic script runs after the glue,
// captures the binding from the shared global scope, and publishes it as a
// window property for the main-thread lyrics loader
// (app/src/lib/playback/lyrics-core.ts). The playback worker keeps using
// importScripts + `new Function` (worker context, no CSP conflict).
const bindingsCapture = join(outDir, 'lyrics-bindings.js');
writeFileSync(
  bindingsCapture,
  `// Generated by scripts/build-wasm.mjs — do not edit.\n` +
    `// Captures the no-modules glue's global-lexical \`wasm_bindgen\` and\n` +
    `// publishes it for the app's main-thread lyrics loader. Loaded as a\n` +
    `// classic script AFTER musicpack_wasm.js (CSP: script-src 'self').\n` +
    `(function () {\n` +
    `  window.__musicpackLyricsWasm = wasm_bindgen;\n` +
    `})();\n`,
);
console.log(`wasm: wrote ${bindingsCapture}`);
