//! Whole-encoder differential oracle (Phase 15G): the Rust PCM → SV8 encoder
//! must reproduce the reference `mpcenc` streams byte-for-byte.
//!
//! The fixtures are committed `.mpc` files generated by the C reference encoder
//! (`tools/gen_encoder_fixtures.py`); this test never invokes C.

use std::path::{Path, PathBuf};

use musicpack_musepack_encoder::encoder::{EncoderConfig, MusepackEncoder};

fn data_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/data/encoder")
}

fn lcg(state: &mut u32) -> u32 {
    *state = state.wrapping_mul(1664525).wrapping_add(1013904223);
    *state
}

fn signed16(state: u32) -> i16 {
    (((state >> 16) & 0xFFFF) as i32 - 32768) as i16
}

/// Deterministic integer-only PCM, matching `tools/gen_encoder_fixtures.py`.
fn gen_pcm(kind: &str, frames: usize) -> Vec<i16> {
    let mut sl = 0x1234_5678u32;
    let mut sr = 0x9ABC_DEF0u32;
    let mut out = Vec::with_capacity(frames * 2);
    for i in 0..frames {
        let (l, r): (i16, i16) = match kind {
            "silence" => (0, 0),
            "impulse" => {
                if i == 0 {
                    (30000, 30000)
                } else {
                    (0, 0)
                }
            }
            "constant" => (12000, 12000),
            "alternating" => {
                if i % 2 == 0 {
                    (8000, 8000)
                } else {
                    (-8000, -8000)
                }
            }
            "ramp" => {
                let v = (((i % 512) as i32 - 256) * 60) as i16;
                (v, v)
            }
            "noise" => (signed16(lcg(&mut sl)), signed16(lcg(&mut sr))),
            "left_only" => (signed16(lcg(&mut sl)), 0),
            "right_only" => (0, signed16(lcg(&mut sr))),
            "phase_invert" => {
                let l = signed16(lcg(&mut sl));
                (l, l.wrapping_neg())
            }
            "transient" => {
                let v = match i {
                    100 => 30000,
                    5000 => -20000,
                    20000 => 25000,
                    _ => 0,
                };
                (v, v)
            }
            other => panic!("unknown kind {other}"),
        };
        out.push(l);
        out.push(r);
    }
    out
}

#[test]
fn whole_encoder_matches_the_reference() {
    let manifest = std::fs::read_to_string(data_dir().join("manifest.txt")).expect("manifest");
    let mut cases = 0usize;
    let mut bytes_total = 0usize;
    let mut first_divergence: Option<String> = None;

    for line in manifest.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let f: Vec<&str> = line.split_whitespace().collect();
        let name = f[0];
        let quality: f32 = f[1].parse().unwrap();
        let rate: u32 = f[2].parse().unwrap();
        let kind = f[3];
        let frames: usize = f[4].parse().unwrap();

        let pcm = gen_pcm(kind, frames);
        let mut enc = MusepackEncoder::new(EncoderConfig::new(quality, rate, 2)).unwrap();
        let actual = enc.encode(&pcm).unwrap();
        let expected = std::fs::read(data_dir().join(format!("{name}.mpc"))).unwrap();

        cases += 1;
        bytes_total += expected.len();

        if actual != expected {
            let first = actual
                .iter()
                .zip(expected.iter())
                .position(|(a, b)| a != b)
                .unwrap_or(actual.len().min(expected.len()));
            let msg = format!(
                "{name}: first divergence at byte {first} (expected {:#04x}, actual {:#04x}); \
                 expected {} bytes, actual {} bytes",
                expected.get(first).copied().unwrap_or(0),
                actual.get(first).copied().unwrap_or(0),
                expected.len(),
                actual.len()
            );
            if first_divergence.is_none() {
                first_divergence = Some(msg.clone());
            }
            eprintln!("MISMATCH {msg}");
        } else {
            eprintln!("ok {name} ({} bytes)", expected.len());
        }
    }

    assert!(cases > 0, "no encoder fixtures found");
    if let Some(msg) = first_divergence {
        panic!("whole-encoder mismatch: {msg}");
    }
    eprintln!("whole encoder: {cases} cases, {bytes_total} bytes matched");
}

/// Trace collection must not alter the encoded bytes: `encode` and
/// `encode_traced` share one implementation and differ only in observation
/// copies. Covers the silence-skipped, short/padded, single-frame and
/// multi-AP-block paths.
#[test]
fn encode_matches_encode_traced() {
    for (kind, frames) in [
        ("silence", 5000),
        ("noise", 1000),
        ("noise", 1152),
        ("noise", 93728),
    ] {
        let pcm = gen_pcm(kind, frames);
        let mut plain = MusepackEncoder::new(EncoderConfig::new(5.0, 44100, 2)).unwrap();
        let mut traced = MusepackEncoder::new(EncoderConfig::new(5.0, 44100, 2)).unwrap();
        let bytes = plain.encode(&pcm).unwrap();
        let (traced_bytes, trace) = traced.encode_traced(&pcm).unwrap();
        assert_eq!(
            bytes, traced_bytes,
            "{kind}/{frames}: traced bytes differ from plain encode"
        );
        assert!(
            !trace.is_empty(),
            "{kind}/{frames}: expected a non-empty trace"
        );
        eprintln!(
            "{kind}/{frames}: identical ({} bytes, {} traced frames)",
            bytes.len(),
            trace.len()
        );
    }
}
