//! Differential replay of the crossfade-mixer oracle.
//!
//! `tests/data/xfade_oracle.jsonl` is generated by `tools/xfade_oracle.ts`,
//! which drives the REAL reference `MusicPackPcmProcessor` over deterministic
//! scripted PCM. This test recreates the same inputs with the Rust
//! [`Mixer`] + [`RingBuffer`] and requires byte-identical mixed output.

use musicpack_core::format::checksum::sha256_hex;
use musicpack_core::json::{self, Value};
use musicpack_engine::mixer::{Mixer, mix_interleaved};
use musicpack_engine::ring::RingBuffer;

fn s<'a>(v: &'a Value, k: &str) -> Option<&'a str> {
    match v.get(k) {
        Some(Value::String(x)) => Some(x.as_str()),
        _ => None,
    }
}
fn n(v: &Value, k: &str) -> Option<f64> {
    match v.get(k) {
        Some(Value::Number(x)) => Some(*x),
        _ => None,
    }
}
fn as_f64(v: &Value) -> Option<f64> {
    match v {
        Value::Number(x) => Some(*x),
        _ => None,
    }
}

fn lcg_next(state: &mut u32) -> u32 {
    *state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
    *state
}

fn generate(kind: &str, frames: usize, channels: usize) -> Vec<f32> {
    let mut out = vec![0.0f32; frames * channels];
    let mut state: u32 = 0x1234_5678;
    for i in 0..frames {
        for c in 0..channels {
            let v: f64 = match kind {
                "silence" => 0.0,
                "dc" => {
                    if c == 0 {
                        0.5
                    } else {
                        -0.5
                    }
                }
                "ramp" => ((i * 2) as f64 - frames as f64) / frames as f64 + c as f64 * 0.1,
                "impulse" => {
                    if i == 0 {
                        1.0
                    } else {
                        0.0
                    }
                }
                _ => {
                    let r = lcg_next(&mut state);
                    (((r >> 8) % 512) as f64) / 256.0 - 1.0
                }
            };
            out[i * channels + c] = v as f32;
        }
    }
    out
}

fn digest(samples: &[f32]) -> String {
    let mut bytes = Vec::with_capacity(samples.len() * 4);
    for s in samples {
        bytes.extend_from_slice(&s.to_le_bytes());
    }
    sha256_hex(&bytes)
}

fn replay(record: &Value) {
    let id = s(record, "id").unwrap();
    let channels = n(record, "channels").unwrap() as usize;
    let fade_frames = n(record, "fadeFrames").unwrap() as u64;
    let out_frames = n(record, "outFrames").unwrap() as usize;
    let in_frames = n(record, "inFrames").unwrap() as usize;
    let kind = s(record, "inputKind").unwrap();

    let outgoing = generate(kind, out_frames, channels);
    let incoming = generate(kind, in_frames, channels);
    assert_eq!(
        digest(&outgoing),
        s(record, "inputOutSha").unwrap(),
        "{id}: input out"
    );
    assert_eq!(
        digest(&incoming),
        s(record, "inputInSha").unwrap(),
        "{id}: input in"
    );

    let capacity = (out_frames.max(in_frames).max(1)) * 2;
    let mut out_ring = RingBuffer::new(capacity, channels).unwrap();
    let mut in_ring = RingBuffer::new(capacity, channels).unwrap();
    out_ring.write_interleaved(&outgoing);
    in_ring.write_interleaved(&incoming);

    let mut mixer = Mixer::new(fade_frames);
    mixer.start(0);
    let mut mixed = vec![0.0f32; fade_frames as usize * channels];
    let mut oframe = vec![0.0f32; channels];
    let mut iframe = vec![0.0f32; channels];
    for frame in 0..fade_frames as usize {
        let Some((out_gain, in_gain)) = mixer.next_gains() else {
            break;
        };
        let has_out = out_ring.read_interleaved(&mut oframe, 1) == 1;
        let has_in = in_ring.read_interleaved(&mut iframe, 1) == 1;
        let dst = &mut mixed[frame * channels..(frame + 1) * channels];
        mix_interleaved(
            dst,
            if has_out { Some(&oframe) } else { None },
            if has_in { Some(&iframe) } else { None },
            out_gain,
            in_gain,
        );
    }

    assert_eq!(
        digest(&mixed),
        s(record, "outputSha").unwrap(),
        "{id}: mixed output"
    );
    let head = match record.get("head") {
        Some(Value::Array(a)) => a.clone(),
        _ => Vec::new(),
    };
    let tail = match record.get("tail") {
        Some(Value::Array(a)) => a.clone(),
        _ => Vec::new(),
    };
    for (i, want) in head.iter().enumerate() {
        let want = as_f64(want).unwrap_or(0.0) as f32;
        assert_eq!(mixed[i].to_bits(), want.to_bits(), "{id}: head[{i}]");
    }
    for (i, want) in tail.iter().enumerate() {
        let want = as_f64(want).unwrap_or(0.0) as f32;
        let idx = mixed.len() - tail.len() + i;
        assert_eq!(mixed[idx].to_bits(), want.to_bits(), "{id}: tail[{i}]");
    }
}

#[test]
fn replays_the_typescript_crossfade_oracle() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/data/xfade_oracle.jsonl"
    );
    let text = std::fs::read_to_string(path).expect("committed xfade oracle");
    let mut count = 0;
    for line in text.lines().filter(|l| !l.trim().is_empty()) {
        let record = json::parse(line.as_bytes()).expect("oracle JSON");
        replay(&record);
        count += 1;
    }
    assert!(count >= 10, "expected a broad mixer corpus, got {count}");
}
