// Copyright (c) 2026, The MusicPack Development Team
// SPDX-License-Identifier: BSD-3-Clause

// R4.4 §13/§14: offline-vs-reference PCM compatibility.
//
// Decodes the committed Musepack fixtures through the *generated browser
// Rust/WASM binding* — the exact module the offline OPFS path loads — and
// checks two things:
//
//   1. The Rust decoder at its native output format reproduces the
//      authoritative libmpcdec oracle (`tests/data/musepack_oracle.jsonl`,
//      generated by `tools/musepack_oracle.mjs` from C libmpcdec) byte for
//      byte. This is the frozen compatibility boundary the Rust decoder is
//      pinned to.
//   2. The synchronous **range-source** path (the OPFS byte adapter) yields
//      exactly the same PCM as the complete-bytes path — the adapter changes
//      *where* bytes come from, never what they decode to.
//
// Skips with a notice when the generated wasm or the oracle corpus is
// unavailable, matching the repository's reference-tooling pattern.

import { existsSync, readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const here = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(here, '../../..');
const GLUE = path.join(ROOT, 'web/app/public/rust/musicpack_wasm.js');
const WASM = path.join(ROOT, 'web/app/public/rust/musicpack_wasm_bg.wasm');
const ORACLE = path.join(ROOT, 'tests/data/musepack_oracle.jsonl');
const FIXTURES = path.join(ROOT, 'tests/fixtures/musepack');

const available =
  existsSync(GLUE) && existsSync(WASM) && existsSync(ORACLE) && existsSync(FIXTURES);

interface OracleEntry {
  file: string;
  sampleRate: number;
  channels: number;
  lengthSamples: number;
  pcmFrames: number;
  pcmSha256: string;
}

function loadOracle(): OracleEntry[] {
  if (!existsSync(ORACLE)) return [];
  return readFileSync(ORACLE, 'utf8')
    .split('\n')
    .filter((line) => line.trim().length > 0)
    .map((line) => JSON.parse(line) as OracleEntry);
}

/** SHA-256 of interleaved little-endian float32 PCM (the oracle's format). */
function digestF32(samples: Float32Array): string {
  const buf = Buffer.alloc(samples.length * 4);
  for (let i = 0; i < samples.length; i++) buf.writeFloatLE(samples[i]!, i * 4);
  return createHash('sha256').update(buf).digest('hex');
}

interface WasmModule {
  initSync(input: { module: WebAssembly.Module }): void;
  decode_open(bytes: Uint8Array, rate: number, channels: number): number;
  decode_info(handle: number): string;
  decode_read(handle: number, frames: number): Float32Array;
  decode_close(handle: number): void;
  WasmEngine: {
    new (rate: number, channels: number): EngineApi;
    newRangeSource(rate: number, channels: number, read: RangeRead): EngineApi;
  };
}

interface EngineApi {
  add_source(url: string, bytes: Uint8Array): void;
  open(itemJson: string): string;
  start(): void;
  play(): void;
  render(frames: number): Float32Array;
  rendered_samples(): number;
  is_output_drained(): boolean;
  take_error(): string | undefined;
  close(): void;
}

type RangeRead = (url: string, offset: number, len: number) => Uint8Array;

function loadWasm(): WasmModule {
  const glue = readFileSync(GLUE, 'utf8');
  // eslint-disable-next-line no-new-func
  const factory = new Function(`${glue}\n;return wasm_bindgen;`);
  const wasm_bindgen = factory() as WasmModule;
  wasm_bindgen.initSync({ module: new WebAssembly.Module(readFileSync(WASM)) });
  return wasm_bindgen;
}

/** Runs a `WasmEngine` to exhaustion, returning the full interleaved PCM. */
function drainEngine(engine: EngineApi): Float32Array {
  const chunks: Float32Array[] = [];
  let total = 0;
  engine.start();
  engine.play();
  for (let guard = 0; guard < 200_000; guard++) {
    const error = engine.take_error();
    if (error) throw new Error(error);
    if (engine.is_output_drained()) break;
    const block = engine.render(1024);
    if (block.length > 0) {
      chunks.push(block);
      total += block.length;
    }
  }
  const out = new Float32Array(total);
  let at = 0;
  for (const chunk of chunks) {
    out.set(chunk, at);
    at += chunk.length;
  }
  return out;
}

function itemJson(url: string, codec: string): string {
  return JSON.stringify({
    id: 't1',
    trackId: 1,
    url,
    kind: 'local-file',
    durationHintSeconds: null,
    title: 'T',
    artist: 'A',
    albumTitle: 'AL',
    codec,
  });
}

describe.skipIf(!available)('offline Rust/WASM PCM fidelity (R4.4)', () => {
  const oracle = available ? loadOracle() : [];

  it('the Rust decoder reproduces the libmpcdec PCM oracle byte for byte', () => {
    const wasm = loadWasm();
    let checked = 0;
    for (const entry of oracle) {
      const file = path.join(FIXTURES, entry.file);
      if (!existsSync(file)) continue;
      const bytes = new Uint8Array(readFileSync(file));
      const handle = wasm.decode_open(bytes, entry.sampleRate, entry.channels);
      try {
        const chunks: Float32Array[] = [];
        let total = 0;
        for (;;) {
          const block = wasm.decode_read(handle, 1152);
          if (block.length === 0) break;
          chunks.push(block);
          total += block.length;
        }
        const pcm = new Float32Array(total);
        let at = 0;
        for (const chunk of chunks) {
          pcm.set(chunk, at);
          at += chunk.length;
        }
        expect(pcm.length).toBe(entry.pcmFrames * entry.channels);
        expect(digestF32(pcm), `pcm mismatch for ${entry.file}`).toBe(entry.pcmSha256);
        checked++;
      } finally {
        wasm.decode_close(handle);
      }
    }
    expect(checked).toBeGreaterThan(0);
  });

  it('the OPFS-style range source decodes identically to complete bytes', () => {
    const wasm = loadWasm();
    const file = path.join(FIXTURES, 'sine44-q5.mpc');
    expect(existsSync(file)).toBe(true);
    const bytes = new Uint8Array(readFileSync(file));
    const url = 't.7.audio';

    // Complete-bytes engine (the network-independent reference path).
    const memory = new wasm.WasmEngine(44100, 2);
    memory.add_source(url, bytes);
    const info = JSON.parse(memory.open(itemJson(url, 'musepack-sv8'))) as {
      lengthSamples: number;
    };
    const memoryPcm = drainEngine(memory);
    memory.close();

    // Range-source engine: a synchronous `read(url, offset, len)` backed by
    // the same bytes — exactly the OPFS sync-access-handle contract.
    const read: RangeRead = (_url, offset, len) => {
      if (offset >= bytes.length) return new Uint8Array(0);
      const end = Math.min(bytes.length, offset + Math.min(len, 64 * 1024));
      return bytes.subarray(offset, end);
    };
    const ranged = wasm.WasmEngine.newRangeSource(44100, 2, read);
    const rangedInfo = JSON.parse(ranged.open(itemJson(url, 'musepack-sv8'))) as {
      lengthSamples: number;
      rate: number;
      channels: number;
    };
    expect(rangedInfo.lengthSamples).toBe(info.lengthSamples);
    expect(rangedInfo.rate).toBe(44100);
    expect(rangedInfo.channels).toBe(2);
    const rangePcm = drainEngine(ranged);
    ranged.close();

    expect(rangePcm.length).toBe(memoryPcm.length);
    expect(rangePcm.length).toBeGreaterThan(0);
    expect(digestF32(rangePcm)).toBe(digestF32(memoryPcm));
  });
});
